version: '3.4'

services:
  orderservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://container_orderservice:5002
      - ConsulConfig__ServiceName=OrderService
      - ConsulConfig__ServiceId=Order
    ports:
      - "5002:5002"
    networks:
      - net_backendservices
    depends_on:
      - web.apigateway
      - s_sqlserver
      - s_consul
      - s_rabbitmq
    external_links:
      - container_graylog
      - s_consul
      - s_rabbitmq
      - s_sqlserver
  
      
  basketservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://container_basketservice:5003
      - ConsulConfig__ServiceName=BasketService
      - ConsulConfig__ServiceId=Basket
    ports:
      - "5003:5003"
    networks:
      - net_backendservices
    depends_on:
      - web.apigateway
      - s_redis
      - s_consul
      - s_rabbitmq
    external_links:
      - container_graylog
      - s_consul
      - s_rabbitmq
      - s_redis


  catalogserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://container_catalogservice:5004
      - ConsulConfig__ServiceName=CatalogService
      - ConsulConfig__ServiceId=Catalog
    ports:
      - "5004:5004"
    networks:
      - net_backendservices
    depends_on:
      - web.apigateway
      - s_sqlserver
      - s_consul
      - s_rabbitmq
    external_links:
      - container_graylog
      - s_consul
      - s_rabbitmq
      - s_sqlserver

  identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://container_identityservice:5005
      - ConsulConfig__ServiceName=IdentityService
      - ConsulConfig__ServiceId=Identity
    ports:
      - "5005:5005"
    networks:
      - net_backendservices
    depends_on:
      - web.apigateway
      - s_sqlserver
      - s_consul
      - s_rabbitmq
    external_links:
      - container_graylog
      - s_consul
      - s_rabbitmq
      - s_sqlserver

  paymentservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001"
    networks:
      - net_backendservices
    depends_on:
      - s_rabbitmq
    external_links:
      - container_graylog
      - s_consul
      - s_rabbitmq

  web.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - net_apigateway
      - net_backendservices

  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2000:2000"
    networks:
      - net_frontend
      - net_apigateway

